.\" Translation 1999 by Piotr Roszatycki
.\" Translation update: Robert Luberda <robert@debian.org>, Mar 2011, ipolish 20110328-1
.\"
.TH POLISH 5 "29 marca 2011" "Projekt Debiana" "Debian"
.SH NAZWA
polish \- lista polskich słów
.SH OPIS
.B /usr/share/dict/polish
to plik ASCII zawierający alfabetyczną listę słów, po jednym słowie
w jednej linii.
.SH PLIKI
.I /etc/dictionaries\-common/words
to symboliczne dowiązanie do pliku
.IR /usr/share/dict/<język> .
.I /usr/share/dict/words
to symboliczne dowiązanie do pliku
.IR /etc/dictionaries\-common/words .
To dowiązanie powinno być używane przez oprogramowanie, które
korzysta z systemowej listy słów.
Zajrzyj do
.BR select\-default\-wordlist (8)
po więcej informacji.
.PP
Katalog 
.I /usr/share/dict
może zawierać listy słów dla wielu języków, gdzie nazwa języka jest
określona w języku angielskim, np.
.I /usr/share/dict/french
i
.IR /usr/share/dict/danish ,
jeżeli istnieją, to zawierają odpowiednio listę słów francuskich i duńskich.
Lista słów powinna być zakodowana w standardzie UTF-8.
.SH "ZOBACZ TAKŻE"
.BR ispell (1),
.BR select\-default\-wordlist (8)
oraz
.I Filesystem Hierarchy
.IR Standard .
.SH HISTORIA
Listy słów nie są specyfiką systemu i mogą pochodzić z różnych źródeł.
.PP
Jako systemowa lista słów używany był plik
.IR /usr/\&dict/words .
Ze względów kompatybilności, oprogramowanie powinno sprawdzać
tę lokalizację, gdy
.I /usr/share/dict/words
nie istnieje.
.SH AUTOR
Listy słów mogą mieć różnych autorów.
